version: '3.3'
services:
  www-ngrok:
    image: ${NGROK_IMAGE:-wernight}/ngrok:latest
    networks:
      - tyk
    ports:
      - 4040:4040
    environment:
      - NGROK_PORT=tyk-gateway:8080
    deploy:
      restart_policy:
        condition: on-failure
